          
                          import React, {useState,useEffect} from 'react';
import {View,Text,TextInput,TouchableOpacity,ScrollView,Alert,StyleSheet} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';

export default function App(){
  const [user,setUser]=useState(null); const [email,setEmail]=useState('');
  const [escrows,setEscrows]=useState([]); const [wallets,setWallets]=useState({}); // email => balance
  const [holds,setHolds]=useState({}); // escrow_id => amount locked
  const [view,setView]=useState('orders'); const [sel,setSel]=useState(null);
  const [buyerEmail,setBuyerEmail]=useState(''); const [amount,setAmount]=useState(''); const [item,setItem]=useState(''); const [joinId,setJoinId]=useState(''); const [fundAmt,setFundAmt]=useState('');

  useEffect(()=>{(async()=>{ const u=await AsyncStorage.getItem('u'); const e=await AsyncStorage.getItem('e'); const w=await AsyncStorage.getItem('w'); const h=await AsyncStorage.getItem('h'); if(u) setUser(JSON.parse(u)); if(e) setEscrows(JSON.parse(e)); if(w) setWallets(JSON.parse(w)); if(h) setHolds(JSON.parse(h)); })()},[]);
  const saveW=async(n)=>{setWallets(n); await AsyncStorage.setItem('w',JSON.stringify(n));}
  const saveE=async(n)=>{setEscrows(n); await AsyncStorage.setItem('e',JSON.stringify(n));}
  const saveH=async(n)=>{setHolds(n); await AsyncStorage.setItem('h',JSON.stringify(n));}

  const myBalance = wallets[user?.email] || 0;
  const myOrders = escrows.filter(e=> e.sellerEmail===user?.email || e.buyerEmail===user?.email);

  const login=async()=>{ if(!email.includes('@')) return Alert.alert('Email'); const u={email:email.toLowerCase()}; setUser(u); await AsyncStorage.setItem('u',JSON.stringify(u)); if(!wallets[u.email]){ const nw={...wallets,[u.email]:0}; await saveW(nw);} }

  const fundWallet=async()=>{
    const amt=parseInt(fundAmt); if(!amt) return Alert.alert('Amount');
    // REAL Paystack here: initialize transaction with amt*100
    // For now simulate Paystack credit:
    const nw={...wallets,[user.email]:(wallets[user.email]||0)+amt};
    await saveW(nw); setFundAmt('');
    Alert.alert('Wallet Funded ✅','Paystack credited your EscrowLock wallet N'+amt+'\nIn production: Paystack Checkout -> webhook -> credit wallet');
  }

  const createOrder=async()=>{
    const id='ESC-'+Math.floor(100000+Math.random()*900000);
    const o={id,sellerEmail:user.email,buyerEmail:buyerEmail.toLowerCase(),amount:parseInt(amount),item,status:'WAITING',createdAt:Date.now()};
    await saveE([...escrows,o]); Alert.alert('Created '+id,'Send to buyer on WhatsApp');
  }

  const payFromWallet=async()=>{
    if(myBalance < sel.amount) return Alert.alert('Insufficient Wallet','Fund wallet first. Balance N'+myBalance);
    // Move from buyer wallet to HOLD (Paystack holds)
    const nw={...wallets,[user.email]:wallets[user.email]-sel.amount};
    await saveW(nw);
    const nh={...holds,[sel.id]:sel.amount};
    await saveH(nh);
    const upd=escrows.map(e=>e.id===sel.id?{...e,status:'LOCKED'}:e);
    await saveE(upd); setSel({...sel,status:'LOCKED'});
    Alert.alert('Locked in Escrow 🔒','N'+sel.amount+' moved from your wallet to Escrow HOLD (Paystack holds). Seller will deliver now.');
  }

  const confirmDelivery=async()=>{
    const amt=holds[sel.id];
    // Move HOLD to seller wallet (Paystack credits seller wallet)
    const sellerBal = wallets[sel.sellerEmail]||0;
    const nw={...wallets,[sel.sellerEmail]:sellerBal+amt};
    await saveW(nw);
    const nh={...holds}; delete nh[sel.id]; await saveH(nh);
    const upd=escrows.map(e=>e.id===sel.id?{...e,status:'RELEASED'}:e);
    await saveE(upd); setSel({...sel,status:'RELEASED'});
    Alert.alert('Delivered ✅','Paystack credited Seller EscrowLock wallet N'+amt+'. Seller can withdraw to any bank.');
  }

  const withdraw=async()=>{
    if(myBalance===0) return Alert.alert('No funds');
    // REAL: Paystack Transfer API here - POST /transferrecipient then /transfer
    const nw={...wallets,[user.email]:0};
    await saveW(nw);
    Alert.alert('Withdrawal Initiated','N'+myBalance+' sent to your bank via Paystack Transfer API. Check Opay/GTB.\nIn prod: call Paystack transfer recipient + transfer');
  }

  if(!user) return <View style={s.c}><Text style={s.h1}>EscrowLock Wallet</Text><Text style={s.sm}>Buyer funds wallet first, then pays seller via escrow. Seller withdraws to any bank.</Text><TextInput style={s.in} placeholder="Email" value={email} onChangeText={setEmail} autoCapitalize='none'/><TouchableOpacity style={s.btn} onPress={login}><Text style={s.bt}>Enter</Text></TouchableOpacity></View>;

  return(
    <View style={s.c}>
      <Text style={s.h2}>EscrowLock • Wallet Model</Text><Text style={s.sm}>{user.email} • Wallet N{myBalance.toLocaleString()}</Text>
      <View style={s.tabs}><TouchableOpacity style={[s.tab,view==='orders'&&s.ta]} onPress={()=>setView('orders')}><Text>Orders</Text></TouchableOpacity><TouchableOpacity style={[s.tab,view==='wallet'&&s.ta]} onPress={()=>setView('wallet')}><Text>Wallet</Text></TouchableOpacity><TouchableOpacity style={[s.tab,view==='create'&&s.ta]} onPress={()=>setView('create')}><Text>Create</Text></TouchableOpacity><TouchableOpacity style={[s.tab,view==='join'&&s.ta]} onPress={()=>setView('join')}><Text>Join</Text></TouchableOpacity></View>
      <ScrollView>
        {view==='wallet' && <View style={s.card}><Text style={s.b}>My EscrowLock Wallet (Paystack Balance)</Text><Text style={s.big}>N{myBalance.toLocaleString()}</Text><TextInput style={s.in} placeholder="Amount to fund e.g. 100000" value={fundAmt} onChangeText={setFundAmt} keyboardType='numeric'/><TouchableOpacity style={s.btn} onPress={fundWallet}><Text style={s.bt}>Fund Wallet via Paystack</Text></TouchableOpacity><TouchableOpacity style={[s.btn,{backgroundColor:'#0a7'}]} onPress={withdraw}><Text style={s.bt}>Withdraw N{myBalance} to Any Bank (Opay/GTB)</Text></TouchableOpacity><Text style={s.sm}>Flow: Paystack Checkout -> Your Paystack balance holds money -> Transfer API to user's bank on withdraw</Text></View>}
        {view==='orders' && myOrders.map(o=><TouchableOpacity key={o.id} style={s.card} onPress={()=>{setSel(o); setView('detail')}}><Text style={s.b}>{o.id} - {o.item}</Text><Text>N{o.amount} - {o.status} {holds[o.id]? `(HOLD N${holds[o.id]})`:''}</Text></TouchableOpacity>)}
        {view==='create' && <><TextInput style={s.in} placeholder="Buyer Email" value={buyerEmail} onChangeText={setBuyerEmail}/><TextInput style={s.in} placeholder="Amount" value={amount} onChangeText={setAmount} keyboardType='numeric'/><TextInput style={s.in} placeholder="Item/Property" value={item} onChangeText={setItem}/><TouchableOpacity style={s.btn} onPress={createOrder}><Text style={s.bt}>Create ESC ID</Text></TouchableOpacity></>}
        {view==='join' && <><TextInput style={s.in} placeholder="ESC ID" value={joinId} onChangeText={setJoinId} autoCapitalize='characters'/><TouchableOpacity style={s.btn} onPress={()=>{ const f=escrows.find(e=>e.id===joinId.toUpperCase()); if(!f) return Alert.alert('Not found'); setSel(f); setView('detail');}}><Text style={s.bt}>Join</Text></TouchableOpacity></>}
        {view==='detail' && sel && <View style={s.card}><Text style={s.b}>{sel.id}</Text><Text>Item: {sel.item} N{sel.amount}</Text><Text>Status: {sel.status}</Text><Text style={s.sm}>Your Wallet N{myBalance}</Text>{sel.status==='WAITING' && sel.buyerEmail===user.email && <TouchableOpacity style={s.btn} onPress={payFromWallet}><Text style={s.bt}>Pay N{sel.amount} FROM MY WALLET to Escrow HOLD</Text></TouchableOpacity>}{sel.status==='LOCKED' && sel.buyerEmail===user.email && <TouchableOpacity style={[s.btn,{backgroundColor:'#0a7'}]} onPress={confirmDelivery}><Text style={s.bt}>I Got Goods - Delivered - Credit Seller Wallet</Text></TouchableOpacity>}{sel.status==='LOCKED' && <Text style={s.warn}>HOLD: N{holds[sel.id]||sel.amount} locked in Paystack. Awaiting buyer confirmation.</Text>}{sel.status==='RELEASED' && <Text style={s.ok}>✅ Seller wallet credited. Can withdraw to any bank.</Text>}</View>}
      </ScrollView>
    </View>
  );
}
const s=StyleSheet.create({c:{flex:1,padding:12,paddingTop:35,backgroundColor:'#f5f6f8'},h1:{fontSize:20,fontWeight:'bold'},h2:{fontWeight:'bold'},b:{fontWeight:'bold'},sm:{fontSize:11,color:'#666'},big:{fontSize:22,fontWeight:'bold'},tabs:{flexDirection:'row',backgroundColor:'#ddd',borderRadius:8,marginVertical:8},tab:{flex:1,padding:10,alignItems:'center'},ta:{backgroundColor:'#111'},in:{backgroundColor:'#fff',borderWidth:1,borderColor:'#ddd',borderRadius:8,padding:12,marginVertical:5},btn:{backgroundColor:'#111',padding:13,borderRadius:8,alignItems:'center',marginVertical:6},bt:{color:'#fff',fontWeight:'bold'},card:{backgroundColor:'#fff',padding:12,borderRadius:10,marginVertical:5},warn:{backgroundColor:'#fff3cd',padding:8,borderRadius:6,marginTop:6},ok:{color:'green',fontWeight:'bold'}});
                    
                  
                      
              
                              

                                          
                            
                                                  
                                                    
                                                                
                                                                
                                                                    
                                                                          
                                                                                      
                                                                                  
                                                                                            
                                                                                              
                                                                                              

                                                                                                    
                                                                                            
                                                                    
                                                                                                    
                                                                                                      
                                                                                                                
                                                                                                                        
                                                                                                                    
                                                                                                                                      

                                                                            
                                                                                                                                        

                                                                                                                      
                                                                                                                                
                                                                                                                                    
                                                                                                                              
                                                                                                                                            
                                                                                                                                        
                                                                                                                                      
                                                                                                                                        
                                                                                                                                                      
                                                                                                                                                                
                                                                                                                                                                            
                                                                                                                                                                          
                                                                                                                                                              
                                                                                                                                                                    
                                                                                                                                                                                                       
                                                                                                                                                                                                            
                                                                                                                                                                                                            

                                                                                                                                                                                      
                                                                                                                                                                                        
                                                                                                                                                                                                            
                                                                                                                                                                                                         
                                                                                                                                                                                                                    
                                                                                                                                                                                                                   
                                                                                                                                                                                                                 
                                                                                                                                                                                                                                
                                                                                                                                                                                                                        
                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                           
                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                        

                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                  

                                                                                                                                                                                                                                                                                                                                   

                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                

                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              header:{flexDirection:'row', justifyContent:'space-between', alignItems:'center', marginBottom:10}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
